In [1]:
import numpy as np
import pandas as pd

In [2]:
company = pd.read_csv("Fortune.csv", encoding='latin1')

In [3]:
company.head()

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,Walmart,"23,00,000",1.0,"$4,85,873",0.8%,"$13,643.0",-7.2%,"$1,98,825","$2,18,619"
1,2,Berkshire Hathaway,"3,67,700",4.0,"$2,23,604",6.1%,"$24,074.0",0.0%,"$6,20,854","$4,11,035"
2,3,Apple,"1,16,000",3.0,"$2,15,639",-7.7%,"$45,687.0",-14.4%,"$3,21,686","$7,53,718"
3,4,Exxon Mobil,"72,700",2.0,"$2,05,004",-16.7%,"$7,840.0",-51.5%,"$3,30,314","$3,40,056"
4,5,McKesson,"68,000",5.0,"$1,92,487",6.2%,"$2,258.0",53.0%,"$56,563","$31,439"

In [ ]:
company.columns

Index(['Rank', 'Company Name', 'Number of Employees', 'Previous Rank',
       'Revenues', 'Revenue Change', 'Profits', 'Profit Change', 'Assets',
       'Market Value'],
      dtype='str')

In [14]:
rank = company.groupby('Company Name')

In [15]:
rank

In [16]:
len(rank)

497

In [19]:
rank.size().sort_values(ascending=False)

Company Name
Avnet                  2
Alcoa                  2
Regions Financial      2
Whirlpool              1
W.R. Berkley           1
                      ..
Activision Blizzard    1
Adobe Systems          1
Advance Auto Parts     1
Aetna                  1
Weyerhaeuser           1
Length: 497, dtype: int64

In [20]:
rank.first()

,Rank,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
Company Name,,,,,,,,,
3M,94,"91,584",93.0,"$30,109",-0.5%,"$5,050.0",4.5%,"$32,906","$1,14,338"
A-Mark Precious Metals,395,"83,000",426.0,"$6,784",11.8%,$9.3,31.5%,$437,$120
ABM Industries,500,"1,10,000",485.0,"$5,145",-2.8%,$57.2,-25.0%,"$2,281","$2,428"
ADP,240,"57,000",248.0,"$11,668",1.7%,"$1,492.5",2.8%,"$43,670","$45,963"
AECOM,161,"87,000",156.0,"$17,411",-3.2%,$96.1,-,"$13,727","$5,528"
...,...,...,...,...,...,...,...,...,...
Yum China Holdings,399,"4,20,000",NaN,"$6,752",-,$502.0,-,"$3,727","$10,453"
Zimmer Biomet Holdings,352,"18,500",431.0,"$7,684",28.1%,$305.9,108.1%,"$26,684","$24,571"
eBay,310,"12,600",300.0,"$8,979",-5.4%,"$7,266.0",321.2%,"$23,847","$36,232"
iHeartMedia,426,"18,700",414.0,"$6,274",0.5%,-$296.3,-,"$12,862",$330
salesforce.com,326,"25,000",386.0,"$8,392",25.9%,$179.6,-,"$17,585","$58,362"

In [22]:
rank.groups

{'3M': [93], 'A-Mark Precious Metals': [394], 'ABM Industries': [499], 'ADP': [239], 'AECOM': [160], 'AES': [193], 'AGCO': [369], 'AIG': [54], 'AK Steel Holding': [440], 'AT&T': [8], 'AbbVie': [110], 'Abbott Laboratories': [134], 'Activision Blizzard': [405], 'Adobe Systems': [442], 'Advance Auto Parts': [291], 'Aetna': [42], 'Aflac': [125], 'Air Products & Chemicals': [293], 'Airgas': [488], 'Alaska Air Group': [437], 'Albertsons Cos.': [48], 'Alcoa': [227, 299], 'Alleghany': [427], 'Alliance Data Systems': [377], 'Allstate': [83], 'Ally Financial': [285], 'Alphabet': [26], 'Altria Group': [147], 'AmTrust Financial Services': [474], 'Amazon.com': [11], 'Ameren': [430], 'American Airlines Group': [66], 'American Electric Power': [166], 'American Express': [85], 'American Family Insurance Group': [314], 'American Financial Group': [410], 'American Tower': [448], 'Ameriprise Financial': [238], 'AmerisourceBergen': [10], 'Amgen': [122], 'Amphenol': [423], 'Anadarko Petroleum': [343], 'Anixter International': [358], 'Anthem': [28], 'Apache': [487], 'Apple': [2], 'Applied Materials': [264], 'Aramark': [191], 'Archer Daniels Midland': [44], 'Arrow Electronics': [117], 'Arthur J. Gallagher': [461], 'Asbury Automotive Group': [409], 'Ascena Retail Group': [383], 'Assurant': [360], 'Auto-Owners Insurance': [397], 'AutoNation': [128], 'AutoZone': [269], 'Autoliv': [282], 'Avery Dennison': [429], 'Avis Budget Group': [318], 'Avnet': [107, 108], 'Avon Products': [443], 'BB&T Corp.': [244], 'Baker Hughes': [284], 'Ball': [305], 'Bank of America Corp.': [25], 'Bank of New York Mellon Corp.': [176], 'Baxter International': [280], 'Becton Dickinson': [224], 'Bed Bath & Beyond': [232], 'Berkshire Hathaway': [1], 'Berry Global Group': [412], 'Best Buy': [71], 'Big Lots': [494], 'Biogen': [247], 'BlackRock': [254], 'Boeing': [23], 'Booz Allen Hamilton Holding': [480], 'BorgWarner': [304], 'Boston Scientific': [326], 'Bristol-Myers Squibb': [146], 'Builders FirstSource': [420], 'Burlington Stores': [462], 'C.H. Robinson Worldwide': [211], 'CBRE Group': [213], 'CBS': [192], 'CDW': [198], 'CH2M Hill': [493], 'CHS': [92], 'CMS Energy': [418], 'CST Brands': [306], 'CSX': [256], 'CVS Health': [6], 'CalAtlantic Group': [414], 'Calpine': [399], 'Campbell Soup': [338], 'Capital One Financial': [99], 'CarMax': [173], 'Cardinal Health': [14], 'CaseyÕs General Stores': [422], ...}

In [4]:
ipl = pd.read_csv("deliveries.csv")

In [5]:
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [6]:
runs = ipl.groupby('batsman')

In [7]:
runs.get_group('V Kohli')

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
2590,12,1,Royal Challengers Bangalore,Mumbai Indians,1,2,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,1,1,NaN,NaN,NaN
2591,12,1,Royal Challengers Bangalore,Mumbai Indians,1,3,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2593,12,1,Royal Challengers Bangalore,Mumbai Indians,1,5,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2594,12,1,Royal Challengers Bangalore,Mumbai Indians,1,6,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2597,12,1,Royal Challengers Bangalore,Mumbai Indians,2,1,V Kohli,CH Gayle,Harbhajan Singh,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150410,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,12,5,V Kohli,AB de Villiers,Bipul Sharma,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150413,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,2,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150414,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,3,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150415,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,4,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150416,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,5,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,0,0,0,V Kohli,bowled,NaN

In [32]:
runs['batsman_runs'].sum().sort_values(ascending=False).head()

batsman
SK Raina     4548
V Kohli      4423
RG Sharma    4207
G Gambhir    4132
DA Warner    4014
Name: batsman_runs, dtype: int64

In [39]:
bowler = ipl.groupby('bowler')

In [41]:
bowler.get_group("TS Mills")

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6367,27,1,Kolkata Knight Riders,Royal Challengers Bangalore,19,2,Kuldeep Yadav,UT Yadav,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
6368,27,1,Kolkata Knight Riders,Royal Challengers Bangalore,19,3,UT Yadav,Kuldeep Yadav,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
6369,27,1,Kolkata Knight Riders,Royal Challengers Bangalore,19,4,UT Yadav,Kuldeep Yadav,TS Mills,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
6370,27,1,Kolkata Knight Riders,Royal Challengers Bangalore,19,5,UT Yadav,Kuldeep Yadav,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
6371,27,1,Kolkata Knight Riders,Royal Challengers Bangalore,19,6,UT Yadav,Kuldeep Yadav,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [48]:
bowler['player_dismissed'].count().sort_values(ascending=False).head(10)

bowler
SL Malinga         170
A Mishra           142
DJ Bravo           137
Harbhajan Singh    136
PP Chawla          133
R Vinay Kumar      125
A Nehra            121
Z Khan             119
B Kumar            117
R Ashwin           110
Name: player_dismissed, dtype: int64

In [51]:
runs['ball'].sum()

batsman
A Ashish Reddy     720
A Chandila          23
A Chopra           273
A Choudhary         71
A Flintoff         203
                  ...
YV Takawale        695
Yashpal Singh      250
Younis Khan         25
Yuvraj Singh      7599
Z Khan             525
Name: ball, Length: 461, dtype: int64

In [52]:
ipl

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [12]:
runs = pd.read_csv("deliveries.csv")

In [20]:
mask = runs['batsman_runs'] == 4
new_delivery = runs[mask]

In [22]:
new_delivery[['batsman', 'batsman_runs']]

              batsman  batsman_runs
2           DA Warner             4
8           DA Warner             4
13       MC Henriques             4
30       MC Henriques             4
32           S Dhawan             4
...               ...           ...
150403        V Kohli             4
150407        V Kohli             4
150418       KL Rahul             4
150447    Sachin Baby             4
150459  Iqbal Abdulla             4

[17033 rows x 2 columns]

In [16]:
mask = runs['batsman_runs'] == 6
new_delivery = runs[mask]

In [31]:
type(new_delivery)

pandas.DataFrame

In [23]:
new_delivery.shape[0]

17033

In [24]:
new_delivery.groupby('batsman')['batsman_runs'].count()

batsman
A Ashish Reddy     16
A Chopra            7
A Choudhary         1
A Flintoff          5
A Kumble            3
                 ...
YK Pathan         240
YV Takawale        26
Yashpal Singh       5
Yuvraj Singh      205
Z Khan             11
Name: batsman_runs, Length: 368, dtype: int64

In [33]:
runs.groupby('batsman')['batsman_runs'].sum()

batsman
A Ashish Reddy     280
A Chandila           4
A Chopra            53
A Choudhary         25
A Flintoff          62
                  ...
YV Takawale        192
Yashpal Singh       47
Younis Khan          3
Yuvraj Singh      2591
Z Khan             117
Name: batsman_runs, Length: 461, dtype: int64

In [36]:
mask = runs['batsman_runs'] == 6
news = runs[mask]

In [40]:
news.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False).head()

batsman
CH Gayle     266
SK Raina     174
RG Sharma    173
DA Warner    160
V Kohli      160
Name: batsman_runs, dtype: int64

In [54]:
mask = runs['dismissal_kind'].isin([
    'bowled',
    'caught',
    'lbw',
    'stumped',
    'caught and bowled',
    'hit wicket'
])
news = runs[mask]

In [53]:
news.groupby('bowler')['player_dismissed'].count().sort_values(ascending=False).head()

bowler
SL Malinga         154
A Mishra           134
Harbhajan Singh    127
PP Chawla          126
DJ Bravo           122
Name: player_dismissed, dtype: int64

In [65]:
news.groupby(['bowler', 'player_dismissed']).size().sort_values(ascending=False).head()

bowler   player_dismissed
Z Khan   MS Dhoni            7
PP Ojha  MS Dhoni            6
B Kumar  AM Rahane           6
A Nehra  V Kohli             6
Z Khan   G Gambhir           6
dtype: int64

In [ ]:
mask = runs['batsman'] == 'V Kohli'
news = runs[mask]

In [84]:
news

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
2590,12,1,Royal Challengers Bangalore,Mumbai Indians,1,2,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,1,1,NaN,NaN,NaN
2591,12,1,Royal Challengers Bangalore,Mumbai Indians,1,3,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2593,12,1,Royal Challengers Bangalore,Mumbai Indians,1,5,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2594,12,1,Royal Challengers Bangalore,Mumbai Indians,1,6,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2597,12,1,Royal Challengers Bangalore,Mumbai Indians,2,1,V Kohli,CH Gayle,Harbhajan Singh,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150410,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,12,5,V Kohli,AB de Villiers,Bipul Sharma,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150413,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,2,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
150414,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,3,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150415,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,4,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150416,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,13,5,V Kohli,AB de Villiers,BB Sran,0,...,0,0,0,0,0,0,0,V Kohli,bowled,NaN

In [94]:
news.groupby(['batsman', 'bowling_team'])['batsman_runs'].sum().head()

batsman  bowling_team
V Kohli  Chennai Super Kings    706
         Deccan Chargers        306
         Delhi Daredevils       661
         Gujarat Lions          283
         Kings XI Punjab        483
Name: batsman_runs, dtype: int64

In [106]:
balls = news.groupby('bowling_team')['batsman_runs'].size()

In [ ]:
balls

bowling_team
Chennai Super Kings        570
Deccan Chargers            230
Delhi Daredevils           485
Gujarat Lions              186
Kings XI Punjab            388
Kochi Tuskers Kerala        52
Kolkata Knight Riders      331
Mumbai Indians             366
Pune Warriors              101
Rajasthan Royals           278
Rising Pune Supergiant      67
Rising Pune Supergiants    128
Sunrisers Hyderabad        312
Name: batsman_runs, dtype: int64

In [114]:
balls = balls[balls >= 100]

In [115]:
balls

bowling_team
Chennai Super Kings        570
Deccan Chargers            230
Delhi Daredevils           485
Gujarat Lions              186
Kings XI Punjab            388
Kolkata Knight Riders      331
Mumbai Indians             366
Pune Warriors              101
Rajasthan Royals           278
Rising Pune Supergiants    128
Sunrisers Hyderabad        312
Name: batsman_runs, dtype: int64

In [ ]:
total_runs = news.groupby('bowling_team')['batsman_runs'].sum()

In [110]:
total_runs

bowling_team
Chennai Super Kings        706
Deccan Chargers            306
Delhi Daredevils           661
Gujarat Lions              283
Kings XI Punjab            483
Kochi Tuskers Kerala        50
Kolkata Knight Riders      391
Mumbai Indians             447
Pune Warriors              128
Rajasthan Royals           258
Rising Pune Supergiant      83
Rising Pune Supergiants    188
Sunrisers Hyderabad        439
Name: batsman_runs, dtype: int64

In [116]:
sr = (total_runs/balls)*100

In [122]:
sr.sort_values(ascending=False)

bowling_team
Gujarat Lions              152.150538
Rising Pune Supergiants    146.875000
Sunrisers Hyderabad        140.705128
Delhi Daredevils           136.288660
Deccan Chargers            133.043478
Pune Warriors              126.732673
Kings XI Punjab            124.484536
Chennai Super Kings        123.859649
Mumbai Indians             122.131148
Kolkata Knight Riders      118.126888
Rajasthan Royals            92.805755
Kochi Tuskers Kerala              NaN
Rising Pune Supergiant            NaN
Name: batsman_runs, dtype: float64